#!/bin/bash

set -e

tmpfile=$(mktemp)
if [ ! -w $tmpfile ] ; then
	echo "Failed to create tmp file" >&2
	exit 0
fi

trap "rm -rf $tmpfile" EXIT # cleanup if aborted

echo "
table ip x {
        chain y {
                define unused = 4.4.4.4
                define address = { 1.1.1.1, 2.2.2.2 }
                ip saddr $address
                redefine address = { 3.3.3.3 }
                ip saddr $address
                undefine unused
        }
}" >> $tmpfile

EXPECTED="table ip x {
        chain y {
                ip saddr { 1.1.1.1, 2.2.2.2 }
                ip saddr { 3.3.3.3 }
        }
}"

$NFT -f $tmpfile

GET="$($NFT list ruleset)"

if [ "$EXPECTED" != "$GET" ] ; then
        DIFF="$(which diff)"
        [ -x $DIFF ] && $DIFF -u <(echo "$EXPECTED") <(echo "$GET")
        exit 1
fi
