#!/bin/bash

set -e
$NFT add table test-ip
$NFT add set test-ip x { type ipv4_addr\; }	# should have handle 1
$NFT add set test-ip y { type inet_service \; timeout 3h45s \;} 	# should have handle 2
$NFT add set test-ip z { type ipv4_addr\; flags constant , interval\;} # should have handle 3
$NFT add set test-ip c {type ipv4_addr \; flags timeout \; elements={192.168.1.1 timeout 10s, 192.168.1.2 timeout 30s} \;} #should have handle 4
$NFT delete set test-ip handle 4

EXPECTED="table ip test-ip {
	set x {
		type ipv4_addr
	}

	set y {
		type inet_service
		timeout 3h45s
	}

	set z {
		type ipv4_addr
		flags constant,interval
	}
}"

GET="$($NFT list ruleset)"

if [ "$EXPECTED" != "$GET" ] ; then
	DIFF="$(which diff)"
	[ -x $DIFF ] && $DIFF -u <(echo "$EXPECTED") <(echo "$GET")
	exit 1
fi
