#!/bin/bash

# Test that comments are added to sets

$NFT add table t
$NFT add set t s {type ipv4_addr \; flags interval \; comment "test" \;}
if ! $NFT list ruleset | grep test >/dev/null ; then
	echo "E: missing comment in set" >&2
	exit 1
fi

